"""
Optimal EMA slope parameters for long trade filtering.

Generated by find_optimal_ema_slope.py
These values will be updated after backtest analysis.
"""

# Default EMA slope filter settings
USE_EMA_SLOPE_FILTER = True  # Enable/disable EMA slope filter for long trades

# Optimal EMA periods and slope thresholds per symbol for LONG trades
# Format: (symbol, direction) -> (ema_period, min_slope_threshold)
OPTIMAL_EMA_PARAMS = {
    # Will be populated after running find_optimal_ema_slope.py
    # Example:
    # ("ETH/EUR", "long"): (100, 0.2),  # EMA-100, slope >= 0.2%
    # ("BTC/EUR", "long"): (120, 0.1),  # EMA-120, slope >= 0.1%
}

# Default fallback values if symbol not found
DEFAULT_EMA_PERIOD = 100
DEFAULT_SLOPE_THRESHOLD = 0.1  # 0.1% minimum upward slope


def get_ema_slope_params(symbol: str, direction: str) -> tuple:
    """
    Get optimal EMA period and slope threshold for a symbol/direction.

    Args:
        symbol: Trading symbol (e.g., "ETH/EUR")
        direction: Trade direction ("long" or "short")

    Returns:
        Tuple of (ema_period, slope_threshold)
    """
    direction = direction.lower()

    # Only apply to long trades
    if direction != "long":
        return None, None

    key = (symbol, direction)
    if key in OPTIMAL_EMA_PARAMS:
        return OPTIMAL_EMA_PARAMS[key]

    # Return defaults for long trades
    return DEFAULT_EMA_PERIOD, DEFAULT_SLOPE_THRESHOLD


def should_filter_entry_by_ema_slope(
    symbol: str,
    direction: str,
    current_slope: float
) -> bool:
    """
    Check if entry should be filtered based on EMA slope.

    Args:
        symbol: Trading symbol
        direction: Trade direction
        current_slope: Current EMA slope (%)

    Returns:
        True if entry should be BLOCKED (slope too flat/negative)
        False if entry is ALLOWED (slope sufficient)
    """
    if not USE_EMA_SLOPE_FILTER:
        return False  # Filter disabled, allow all entries

    ema_period, slope_threshold = get_ema_slope_params(symbol, direction)

    # Only filter long trades
    if ema_period is None or slope_threshold is None:
        return False

    # Check if slope meets minimum threshold
    if current_slope < slope_threshold:
        return True  # BLOCK entry - slope too weak

    return False  # ALLOW entry - slope sufficient
